steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ga4_pii_auditor/ga4-pii-auditor:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ga4_pii_auditor/ga4-pii-auditor:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ga4-pii-auditor'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ga4_pii_auditor/ga4-pii-auditor:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'
      - '--service-account=ga4-pii-auditor-sa@tvc-ga4-pii-auditor.iam.gserviceaccount.com'
      - '--set-env-vars=GCP_PROJECT=$PROJECT_ID'


images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ga4_pii_auditor/ga4-pii-auditor:$COMMIT_SHA'
